Ammunationsimon-main/Ammunation/urls.py
from django.urls import include, path
from .views import index, adminGuns, administrador, modificararma, deleteGuns, deleteUser, descriptionGuns, \
editarPerfil, olvidarcontraseña, verificaremail, register, editarusuario, perfildeusuario, vistaCompras, vistaVender, \
vistaVentas, cerrar_sesion, add_to_cart, update_cart_item, remove_from_cart, carrito, process_payment
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', index, name='index'),
    path('adminGuns/', adminGuns, name='adminGuns'),
    path('administrador/', administrador, name='administrador'),
    path('carrito/', carrito, name='carrito'),
    path('add/<int:arma_id>/', add_to_cart, name='add_to_cart'),
    path('update/<int:item_id>/', update_cart_item, name='update_cart_item'),
    path('remove/<int:item_id>/', remove_from_cart, name='remove_from_cart'),
    path('process_payment/', process_payment, name='process_payment'),
    path('modificararma/<id>', modificararma, name='modificararma'),
    path('deleteGuns/<id>', deleteGuns, name='deleteGuns'),
    path('deleteUser/<id>', deleteUser, name='deleteUser'),
    path('descriptionGuns/<id>', descriptionGuns, name='descriptionGuns'),
    path('editarPerfil/', editarPerfil, name='editarPerfil'),
    path('olvidarcontraseña/', olvidarcontraseña, name='olvidarcontraseña'),
    path('verificaremail/', verificaremail, name='verificaremail'),
    path('register/', register, name='register'),
    path('editarusuario/<id>', editarusuario, name='editarusuario'),
    path('perfildeusuario/', perfildeusuario, name='perfildeusuario'),
    path('vistaCompras/', vistaCompras, name='vistaCompras'),
    path('vistaVender/', vistaVender, name='vistaVender'),
    path('vistaVentas/', vistaVentas, name='vistaVentas'),
    path('cerrar_sesion', cerrar_sesion, name='cerrar_sesion'),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Ammunationsimon-main/sitio/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Ammunation.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

Ammunationsimon-main/Ammunation/models.py
from django.db import models
from .enumeraciones import *
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import User
from django.conf import settings

# Create your models here.
class Perfil(models.Model):
    usuario=models.OneToOneField(User, related_name='usuario', on_delete=models.CASCADE)
    telefono=models.CharField(max_length=9, null=True)
    ciudad=models.CharField(max_length=15, choices=CIUDAD, null=True) 
    direccion=models.CharField(max_length=200, null=True)

class Arma(models.Model):
    nomb_arma=models.CharField(max_length=100, null=False, verbose_name="Nombre")
    categoria=models.CharField(max_length=50, null=False)
    calibre=models.CharField(max_length=13, choices=TIPO_calibre)
    precio=models.PositiveIntegerField(default=0, validators=[MinValueValidator(0),MaxValueValidator(999999)])
    stock=models.PositiveIntegerField(default=1, validators=[MinValueValidator(1),MaxValueValidator(99)])
    descripcion=models.TextField()
    foto_arma=models.ImageField(upload_to='armas',null=False, verbose_name="Imagen")

class CartItem(models.Model):
    arma = models.ForeignKey('Arma', on_delete=models.CASCADE, verbose_name="Arma")
    cantidad = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1)])
    precio_por_item = models.PositiveIntegerField(validators=[MinValueValidator(0)])

    def subtotal(self):
        return self.cantidad * self.precio_por_item

    def __str__(self):
        return f"{self.arma} - {self.cantidad} x {self.precio_por_item}"

class Cart(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="Usuario", related_name="carts")
    items = models.ManyToManyField(CartItem, verbose_name="Ítems", related_name="carts")

    def total(self):
        return sum([item.subtotal() for item in self.items.all()])

    def __str__(self):
        return f"Cart for {self.usuario}"
    
# Ventas
class Venta(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="Usuario")
    arma = models.ForeignKey(Arma, on_delete=models.CASCADE, verbose_name="Arma")
    cantidad = models.PositiveIntegerField()
    total_venta = models.PositiveIntegerField()
    fecha = models.DateTimeField(auto_now_add=True)
    estado = models.CharField(max_length=30, choices=ESTADO, default='EN PREPARACIÓN')

    def total_venta(self):
        return self.cantidad * self.arma.precio 

    def __str__(self):
        return f"Venta {self.id} - {self.arma.nomb_arma} - {self.cantidad} unidades"

Ammunationsimon-main/Ammunation/forms.py
from django import forms
from .models import *
from .enumeraciones import *
from django.contrib.auth.forms import UserCreationForm

# Usuarios
class UserForm(UserCreationForm):
    
    class Meta:
        model=User
        fields=['username', 'first_name', 'last_name', 'email','password1','password2']
        widgets = {
            'password1': forms.PasswordInput(),
            'password2': forms.PasswordInput(),
        }

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['email'].required = True

class PerfilForm(forms.ModelForm):

    class Meta:
        model=Perfil
        fields=['telefono', 'ciudad', 'direccion']

class UpdatePerfilForm(forms.ModelForm):

    class Meta:
        model=Perfil
        fields=['telefono', 'ciudad', 'direccion']

#Armas
class ArmaForm(forms.ModelForm):

    class Meta:
        model = Arma
        fields = ['id', 'nomb_arma', 'categoria', 'calibre', 'precio', 'stock', 'descripcion', 'foto_arma']

class UpdateArmaForm(forms.ModelForm):

    class Meta:
        model = Arma
        fields = ['nomb_arma', 'categoria', 'calibre', 'precio', 'stock', 'descripcion', 'foto_arma']

# Venta
class EstadoVentaForm(forms.ModelForm):
    class Meta:
        model = Venta
        fields = ['estado'] 

Ammunationsimon-main/Ammunation/views.py
from django.shortcuts import render
from django.contrib.auth import logout
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.models import User
from .models import Arma, Perfil, Cart, CartItem, Venta
from .forms import ArmaForm, UpdateArmaForm, UserForm, PerfilForm, UpdatePerfilForm, EstadoVentaForm
from django.contrib import messages
from os import remove, path
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required, permission_required
from django.utils import timezone
from django.db.models import Q
from .viewmodel import MostrarDatosUsuarios

# Create your views here.
def cerrar_sesion(request):
    logout(request)
    return redirect(to='index')

def index(request):
    query = request.GET.get('q')
    calibre = request.GET.get('calibre') 
    
    if query:
        armas = Arma.objects.filter(nomb_arma__icontains=query)
        if not armas.exists():
            armas = Arma.objects.all()
    else:
        armas = Arma.objects.all()
    
    if calibre:
        armas_filtrados = armas.filter(calibre=calibre)
        if armas_filtrados.exists():
            armas = armas_filtrados
    
    datos = {
        "armas": armas
    }

    return render(request,'Ammunation/index.html', datos)

@permission_required('Ammunation.add_arma')
def adminGuns(request):
    query = request.GET.get('q')
    if query:
        armas = Arma.objects.filter(
            Q(nomb_arma__icontains=query) | 
            Q(id__icontains=query) |
            Q(categoria__icontains=query) |
            Q(calibre__icontains=query) |
            Q(precio__icontains=query) |
            Q(stock__icontains=query) |
            Q(descripcion__icontains=query)
        )
        if not armas.exists():
            armas = Arma.objects.all()
    else:
        armas = Arma.objects.all()
    
    datos = {
        "armas": armas
    }

    return render(request,'Ammunation/adminGuns.html', datos)

@permission_required('Ammunation.add_user')
def administrador(request):
    #usuarios = User.objects.all()
    perfiles = Perfil.objects.all()
    
    print("***************************")
    #print(usuarios)
    usuarios_view = []
    for per in perfiles:
        usrview = MostrarDatosUsuarios()
        nombreu=per.usuario.username
        useruser=User.objects.get(username=nombreu)
        idql=str(useruser.id)

        print(idql)
        usrview.id_usuario=idql
        usrview.username=per.usuario.username
        usrview.first_name = per.usuario.first_name
        usrview.last_name =per.usuario.last_name
        usrview.email=per.usuario.email
        usrview.date_joined=per.usuario.date_joined
        usrview.ciudad=per.ciudad
        usrview.direccion=per.direccion
        usrview.telefono=per.telefono
        #print(usrview)
        usuarios_view.append(usrview)
    
    datos={
        "usuarios":usuarios_view
        
    }
    return render(request,'Ammunation/administrador.html', datos)

def carrito(request):
    return render(request,'Ammunation/carrito.html')

@login_required
def add_to_cart(request, arma_id):
    arma = get_object_or_404(Arma, id=arma_id)
    cart, created = Cart.objects.get_or_create(usuario=request.user)

    cart_item, created = CartItem.objects.get_or_create(arma=arma, precio_por_item=arma.precio)
    if not created:
        cart_item.cantidad += 1
        cart_item.save()

    cart.items.add(cart_item)
    messages.success(request, f'{arma.nomb_arma} fue añadido a tu carrito.')

    return redirect('carrito')

@login_required
def carrito(request):
    cart, created = Cart.objects.get_or_create(usuario=request.user)
    return render(request, 'Ammunation/carrito.html', {'cart': cart})

@login_required
def update_cart_item(request, item_id):
    cart_item = get_object_or_404(CartItem, id=item_id)
    if request.method == 'POST':
        cantidad = int(request.POST.get('cantidad', 1))
        cart_item.cantidad = cantidad
        cart_item.save()
        messages.success(request, 'La cantidad fue actualizada.')
    return redirect('carrito')

@login_required
def remove_from_cart(request, item_id):
    cart_item = get_object_or_404(CartItem, id=item_id)
    cart_item.delete()
    messages.success(request, 'El ítem fue eliminado del carrito.')
    return redirect('carrito')

@login_required
def process_payment(request):
    cart, created = Cart.objects.get_or_create(usuario=request.user)
    if not cart.items.exists():
        messages.error(request, 'No tienes artículos en tu carrito.')
        return redirect('carrito')

    for item in cart.items.all():
        arma = item.arma
        if item.cantidad > arma.stock:
            messages.error(request, f'No hay suficiente stock para {arma.nomb_arma}.')
            return redirect('carrito')
        
        Venta.objects.create(
                usuario=request.user,
                arma=arma,
                cantidad=item.cantidad,
                estado='EN PREPARACIÓN',
                fecha=timezone.now()
            )
        
    for item in cart.items.all():
        arma = item.arma
        arma.stock -= item.cantidad
        arma.save()

    cart.items.clear()
    
    messages.success(request, 'Pago realizado con éxito. Gracias por tu compra.')
    return redirect('carrito')

@permission_required('Ammunation.change_arma')
def modificararma(request, id):
    arma = get_object_or_404(Arma, id=id)
    form = UpdateArmaForm(instance=arma)
    
    if request.method=="POST":
        form=UpdateArmaForm(data=request.POST,files=request.FILES,instance=arma)
        if form.is_valid():
            form.save()
            messages.warning(request,"Arma modificada")
            return redirect(to="adminGuns")
    
    datos={
        "form":form,
        "arma":arma
    }

    return render(request, 'Ammunation/modificararma.html', datos)

@permission_required('Ammunation.delete_arma')
def deleteGuns(request, id):
    arma=get_object_or_404(Arma, id=id)
    
    if request.method=="POST":
        remove(path.join(str(settings.MEDIA_ROOT).replace('/media',''))+arma.foto_arma.url)
        arma.delete()
        messages.warning(request,"Arma eliminada")
        return redirect(to="adminGuns")
        
    datos={
        "arma":arma
    }

    return render(request,'Ammunation/deleteGuns.html', datos)

@permission_required('Ammunation.delete_user')
def deleteUser(request, id):
    usuario = get_object_or_404(User, id=id)
    
    if request.method == "POST":
        Perfil.objects.filter(usuario=usuario).delete()
        usuario.delete()
        messages.warning(request, "Usuario eliminado")
        return redirect(to="administrador")
        
    datos = {
        "usuario": usuario
    }

    return render(request,'Ammunation/deleteUser.html', datos)

def descriptionGuns(request, id):
    arma=get_object_or_404(Arma, id=id)
    
    datos={
        "arma":arma
    }

    return render(request,'Ammunation/descriptionGuns.html', datos)

def editarPerfil(request):
    usr = request.user
    perfil_existente = Perfil.objects.filter(usuario=usr).first()

    if request.method == "POST":
        form = PerfilForm(data=request.POST, instance=perfil_existente)
        if form.is_valid():
            perfil = form.save(commit=False)
            perfil.usuario = usr
            perfil.save()
            messages.warning(request,"Perfil modificado")
            return redirect(to="perfildeusuario")
    else:
        if perfil_existente:
            form = PerfilForm(instance=perfil_existente)
        else:
            form = PerfilForm()

    datos = {"form": form}
    return render(request, 'Ammunation/editarPerfil.html', datos)

def olvidarcontraseña(request):
    return render(request,'Ammunation/olvidarcontraseña.html')


def verificaremail(request):
    return render(request,'Ammunation/verificaremail.html')

def register(request):
    form=UserForm()

    if request.method=="POST":
        form=UserForm(data=request.POST)
        if form.is_valid():

            form.save()
            usuarionuevo=get_object_or_404(User,username=form.cleaned_data["username"])
            perfil=Perfil()
            perfil.usuario=usuarionuevo
            perfil.save()
            return redirect(to="login")

    datos={
        "form":form
    }

    return render(request,'registration/register.html', datos)

@permission_required('Ammunation.add_user')
def editarusuario(request, id):
    usuario = get_object_or_404(User, id=id)
    perfil_usuario = get_object_or_404(Perfil, usuario=usuario)
    
    if request.method == "POST":
        form = UpdatePerfilForm(request.POST, instance=perfil_usuario)
        if form.is_valid():
            form.save()
            messages.warning(request, "Usuario modificado")
            return redirect('administrador')
    else:
        form = UpdatePerfilForm(instance=perfil_usuario)

    datos = {
        'form': form
    }

    return render(request,'Ammunation/editarusuario.html', datos)

def perfildeusuario(request):
    usr = request.user
    perfil_usuario, created = Perfil.objects.get_or_create(usuario=usr)
    
    datos = {
        'perfil': perfil_usuario
    }

    return render(request,'Ammunation/perfildeusuario.html', datos)

@login_required
def vistaCompras(request):
    query = request.GET.get('q')
    ventas = Venta.objects.filter(usuario=request.user).order_by('-fecha')

    if query: 
        ventas_filtradas = ventas.filter(
            Q(arma__nomb_arma__icontains=query) |
            Q(arma__calibre__icontains=query) |
            Q(cantidad__icontains=query) |
            Q(estado__icontains=query)
        )
        if ventas_filtradas.exists():
            ventas = ventas_filtradas

    datos = {
        "ventas": ventas
    }

    return render(request, 'Ammunation/vistaCompras.html', datos)


@permission_required('Ammunation.add_arma')
def vistaVender(request):
    form=ArmaForm()

    if request.method=="POST":

Ammunationsimon-main/Ammunation/templates/Ammunation/adminGuns.html
{% extends "Ammunation/base.html" %}
{% load static %}
{% block contenido %}

<title>Administrar armas</title>

{% if perms.Ammunation.add_arma %}
    
    <div class="container mt-3" style="background-color: #343a40; padding: 20px; border-radius: 15px;">
        <p class="mb-0 display-5 text-white">Armas</p>

        <div class="d-flex justify-content-between align-items-center my-3">
            <input type="search" class="form-control w-50" id="adminBuscarArmas" placeholder="Buscar armas" name="q">
            <div class="btn-group">
                <a href="{% url 'vistaVender' %}" class="btn btn-dark">Crear producto</a>
                <a href="{% url 'vistaVentas' %}" class="btn btn-dark mx-3">Ver ventas</a>
                <a href="{% url 'administrador' %}" class="btn btn-dark">Administrar usuarios</a>
                <a href="{% url 'adminGuns' %}" class="btn btn-dark mx-1">Administrar armas</a>
            </div>
        </div>

        <div class="table-responsive my-3">
            <table class="table">
                <thead class="thead-light">
                    <tr>
                        <th>ID</th>
                        <th>Nombre</th>
                        <th>Género</th>
                        <th>calibre</th>
                        <th>Precio</th>
                        <th>Stock</th>
                        <th>Descripción</th>
                        <th>Imagen</th>
                        <th>Acción</th>
                    </tr>
                </thead>
                <tbody class="text-white">
                    {% for j in armas %}
                        <tr>
                            <td>{{ j.id }}</td>
                            <td>{{ j.nomb_arma }}</td>
                            <td>{{ j.categoria }}</td>
                            <td>{{ j.calibre }}</td>
                            <td>${{ j.precio }}</td>
                            <td>{{ j.stock }}</td>
                            <td>{{ j.descripcion }}</td>
                            <td><img src="{{ j.foto_arma.url }}" class="img-fluid rounded" alt="imagen-arma" style="width: 65px;"></td>
                            <td class="text-center">
                                <a href="{% url 'modificararma' j.id %}" class="btn btn-success btn-sm mx-1"><i></i> Editar</a>
                                <a href="{% url 'deleteGuns' j.id %}" class="btn btn-danger btn-sm mx-1"><i></i> Eliminar</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endif %}

{% endblock contenido %}

Ammunationsimon-main/Ammunation/templates/Ammunation/administrador.html
{% extends "Ammunation/base.html" %}
{% load static %}
{% block contenido %}

<title>Administrar usuarios</title>

{% if perms.Ammunation.add_user %}
   
    <div class="container mt-3">
        <p class="mb-0 display-5">Usuarios</p>
        <div class="btn-group my-4">
            <a href="{% url 'administrador' %}" class="btn btn-outline-dark mx-1">Administrar usuarios</a>
            <a href="{% url 'adminGuns' %}" class="btn btn-outline-dark mx-1">Administrar armas</a>
        </div>
        <form class="form-inline mt-3">
            <input type="text" class="form-control mb-2 mr-sm-2" id="adminBuscarUser" placeholder="Buscar usuario" method="GET" name="q">
            <a href="{% url 'register' %}" class="btn btn-outline-dark mb-2">Crear usuario</a>
        </form>
        <div class="table-responsive my-3">
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th>ID</th>
                        <th>Nombre</th>
                        <th>Apellido</th>
                        <th>Nombre de usuario</th>
                        <th>Correo electrónico</th>
                        <th>Número de telefóno</th>
                        <th>Ciudad</th>
                        <th>Dirección</th>
                        <th>Fecha de registro</th>
                        <th>Acción</th>
                    </tr>
                </thead>
                <tbody>
                    {% for usuario in usuarios %}
                        <tr>
                            <td>{{ usuario.id_usuario }}</td>
                            <td>{{ usuario.first_name }}</td>
                            <td>{{ usuario.last_name }}</td>
                            <td>{{ usuario.username }}</td>
                            <td>{{ usuario.email }}</td>
                            <td>+569 {{ usuario.telefono }}</td>
                            <td>{{ usuario.ciudad }}</td>
                            <td>{{ usuario.direccion }}</td>
                            <td>{{ usuario.date_joined }}</td>
                            <td class="text-center">
                                <a href="{% url 'editarusuario' usuario.id_usuario %}" class="btn btn-success btn-sm mx-1"><i></i> Editar</a>
                                <a href="{% url 'deleteUser' usuario.id_usuario %}" class="btn btn-danger btn-sm mx-1"><i></i> Eliminar</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endif %}
{% endblock contenido %}

Ammunationsimon-main/Ammunation/templates/Ammunation/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href='{% static "Ammunation/css/bootstrap.min.css" %}'>
    <link rel="stylesheet" href='{% static "Ammunation/css/stylesapi.css" %}'>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Jersey+10+Charted&display=swap" rel="stylesheet">
    <link rel="shortcut icon" type="image/jpg" href="{% static 'Ammunation/img/Ammu-nation.webp' %}"/>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    {% block importscss %}

    {% endblock importscss %}
    <style>
        .text-red {
            color: red !important;
        }
        .navbar-nav .nav-link {
            color: red !important;
        }
        .user-icons {
            display: flex;
            justify-content: center;
            align-items: center;
        }
        .user-icons .cart {
            font-size: 1.5em;
            margin-left: 15px;
        }
    </style>
</head>

<body style="background-color: #eee;">  
    <nav class="navbar navbar-expand-md bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand d-flex align-items-center" href="{% url 'index' %}">
                <img src="{% static 'Ammunation/img/Ammu-nation.webp' %}" alt="Ammunation logo" style="margin-right: 10px;"> 
                <h4 class="text-white" style="margin: 0">Ammunation</h4>
            </a>
            <button class="navbar-toggler bg-white" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link text-red active" aria-current="page" href="{% url 'index' %}">Inicio</a>
                    </li>
                    {% if perms.Ammunation.add_arma %}
                        <li class="nav-item">
                            <a class="nav-link text-red" href="{% url 'administrador' %}">Admin</a>
                        </li>
                    {% endif %}
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link text-red" href="{% url "perfildeusuario" %}">Bienvenido <div class="text-primary">{{user.username}}</div></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-red" href="{% url 'cerrar_sesion' %}">Cerrar sesión</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link text-red" href="{% url 'login' %}">Iniciar sesión</a>
                        </li>
                    {% endif %}
                    {% if not user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link text-red" href="{% url 'register' %}">Registrarse</a>
                        </li>
                    {% endif %}
                </ul>
                <div class="user-icons">
                    <a href="{% url 'carrito' %}">
                        <div class="cart"><i class="bi bi-cart-fill" style="color:red;"></i></div>
                    </a>
                </div>
            </div>
        </div>
    </nav>
    {% if messages %}
        {% for message in messages %}
            {% if message.level == 25 %}
                <script>
                    Swal.fire({
                        title: 'Exitoso',
                        text: '{{message}}',
                        icon: 'success',
                        confirmButtonText: 'Aceptar'
                    })
                </script>
            {% endif %}

            {% if message.level == 30 %}
                <script>
                    Swal.fire({
                        title: 'Realizado',
                        text: '{{message}}',
                        icon: 'warning',
                        confirmButtonText: 'Aceptar'
                    })
                </script>
            {% endif %}

            {% if message.level == 40 %}
                <script>
                    Swal.fire({
                        title: 'Error',
                        text: '{{message}}',
                        icon: 'error',
                        confirmButtonText: 'Aceptar'
                    })
                </script>
            {% endif %}
        {% endfor %}
    {% endif %}
            
    {% block contenido %} 
    
    {% endblock contenido %}

    
</body>

</html>

Ammunationsimon-main/Ammunation/templates/Ammunation/vistaVentas.html
{% extends "Ammunation/base.html" %}
{% load static %}
{% block contenido %}

<title>Ventas</title>
{% if perms.Ammunation.view_venta %}
    <div class="container mt-5">
        <h2 class="text-center mb-4">Ventas</h2>
        <div class="d-flex justify-content-between align-items-center mb-4">
            <a href="{% url 'adminGuns' %}" class="btn btn-dark">Volver</a>
            <form method="get" class="w-50">
                <div class="input-group">
                    <input type="text" class="form-control" name="q" placeholder="Buscar venta" aria-label="Buscar" value="{{ request.GET.q }}">
                    <div class="input-group-append">
                        <button class="btn btn-outline-secondary" type="submit">Buscar</button>
                    </div>
                </div>
            </form>
        </div>

        <div class="table-responsive">
            <table class="table table-hover table-bordered">
                <thead class="thead-dark">
                    <tr>
                        <th>ID venta</th>
                        <th>ID arma</th>
                        <th>Nombre arma</th>
                        <th>Calibre</th>
                        <th>Cantidad vendida</th>
                        <th>Total venta</th>
                        <th>Usuario</th>
                        <th>Email usuario</th>
                        <th>Estado</th>
                        <th>Fecha venta</th>
                    </tr>
                </thead>
                <tbody>
                    {% for venta in ventas %}
                        <tr>
                            <td>{{ venta.id }}</td>
                            <td>{{ venta.arma.id }}</td>
                            <td>{{ venta.arma.nomb_arma }}</td>
                            <td>{{ venta.arma.calibre }}</td>
                            <td>{{ venta.cantidad }}</td>
                            <td>$ {{ venta.total_venta }}</td>
                            <td>{% if venta.usuario %}{{ venta.usuario.username }}{% else %}Usuario eliminado{% endif %}</td>
                            <td>{% if venta.usuario %}{{ venta.usuario.email }}{% else %}N/A{% endif %}</td>
                            <td>
                                <form method="post" action="">
                                    {% csrf_token %}
                                    <input type="hidden" name="venta_id" value="{{ venta.id }}">
                                    <select name="estado" class="form-control" onchange="this.form.submit()">
                                        <option value="EN PREPARACIÓN" {% if venta.estado == 'EN PREPARACIÓN' %}selected{% endif %}>EN PREPARACIÓN</option>
                                        <option value="PREPARADO" {% if venta.estado == 'PREPARADO' %}selected{% endif %}>PREPARADO</option>
                                        <option value="ENVIADO" {% if venta.estado == 'ENVIADO' %}selected{% endif %}>ENVIADO</option>
                                        <option value="ENTREGADO" {% if venta.estado == 'ENTREGADO' %}selected{% endif %}>ENTREGADO</option>
                                    </select>
                                </form>
                            </td>
                            <td>{{ venta.fecha }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endif %}

{% endblock contenido %}